services:
  # Django Backend
  backend:
    build: ./vibe-search-backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py prepopulate_gallery &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./vibe-search-backend:/app
      - uploads_data:/app/media/uploads
    ports:
      - "8000:8000"
    env_file:
      - ./vibe-search-backend/.env
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=vibesearch.settings
      - SCRAPINGBEE_API_KEY=DGQAE9RYPCV7J6C2AMGV1H2OBV3BMAJ8P4NKVH6WBVRAF4RIV38BFVN2WKPFTE707RAAE9NX8DWKCPYN
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,0.0.0.0

  # Next.js Frontend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - uploads_data:/app/public/uploads  # Shared volume for uploads
    ports:
      - "3000:3000"
    environment:
      - DJANGO_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    command: npm run dev

volumes:
  uploads_data:
